### ISSUE TITLE
Cluster ability like in quartz-1.0.2?

### ISSUE THREAD

**Issue by dtamm** [grails3-plugins/quartz#1]
Just wanted to know, if the new grails3-plugin/quartz already has the same ability to be clustered, like in the quartz-1.0.2 plugin for Grails 2.4.4 (via QuatzConfig.groovy and grails-app/conf/quartz/quartz.properties), since i couldn't find the reference to the quartz.properties file in the plugin files...

If the cluster ability is already given, is it to be implemented the same way as in the former grails 2 plugin?

**Comment by jeffscottbrown** [comment]
I don't know the answer but the mailing list at https://groups.google.com/forum/#!forum/grails-dev-discuss is a better forum for asking questions.  Please file issues for bug reports and feature requests.

**Comment by dtamm** [comment]
Okay, no problem!
