### ISSUE TITLE
Feature request - Make config available for reading triggers

### ISSUE THREAD

**Issue by anshbansal** [grails3-plugins/quartz#12]
Currently when the jobs are started the config is not available. Due to this the triggers cannot be made a part of the config and needs to be either hard-coded or manually read from a config file. 

It would be good if config is available when triggers are evaluated.

**Comment by bobbywarner** [comment]
@anshbansal This fork repo is no longer being used.  Would you mind recreating this issue in the main repo (https://github.com/grails-plugins/grails-quartz)?

**Comment by anshbansal** [comment]
created
https://github.com/grails-plugins/grails-quartz/issues/33
