### ISSUE TITLE
autoStartup configuration not working in 2.0.0

### ISSUE THREAD

**Issue by xardas008** [grails3-plugins/quartz#17]
Hi,

I've set the quartz.autoStartup according to the docs to false, but the scheduler is still running.

I'm using the quartz plugin in version 2.0.0 inside a grails3 application.

Regards

**Comment by bobbywarner** [comment]
@xardas008 This fork repo is no longer being used.  Would you mind recreating this issue in the main repo (https://github.com/grails-plugins/grails-quartz)?

**Comment by bobbywarner** [comment]
Closing as the fix was merged in #18
