### ISSUE TITLE
Job not running on Grails 3.0.1

### ISSUE THREAD

**Issue by develmac** [grails3-plugins/quartz#8]
Hi!

Could you please clarify on how to make the jobs run under Grails3? 

Adding
quartz:
    autoStartup: true

to the applicaiton.yml does not work :(

The Job simply don't run :(

THX!

**Comment by jeffscottbrown** [comment]
I can't reproduce the problem with Grails 3.0.1.  See the sample project at https://github.com/jeffbrown/demoquartz.  
The relevant bits are at https://github.com/jeffbrown/demoquartz/blob/188daeaaa65863b69d0fa38d8e77910f1c4e9743/build.gradle#L74 and https://github.com/jeffbrown/demoquartz/blob/188daeaaa65863b69d0fa38d8e77910f1c4e9743/grails-app/jobs/demo/PrinterJob.groovy#L5.  

When I run that app the job does run as expected.

```
$ ./gradlew run
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:findMainClass
:run
Grails application running at http://localhost:8080
PrinterJob Is Running.
PrinterJob Is Running.
PrinterJob Is Running.
PrinterJob Is Running.
PrinterJob Is Running.
PrinterJob Is Running.
PrinterJob Is Running.
```

Can you verify that you have a compile time dependency on the quartz plugin and that your job schedule is set?  If you can push a sample app to github which demonstrates the problem, I will be happy to look at it.

**Comment by jeffscottbrown** [comment]
It is important that the dependency be expressed as a `compile` dependency, not a `runtime` dependency.  That is one thing to look for.

**Comment by develmac** [comment]
THX, got it running! It was strange somehow, after a gradle clean it worked...

**Comment by ppazos** [comment]
It is worth mentioning that quartz versions from 2.0.1 to 2.0.5 are broken. It seems from 2.0.6 it start to work Ok, and before 2.0.1 worked OK.
