### ISSUE TITLE
Where to contribute to quartz plugin documentation?

### ISSUE THREAD

**Issue by anshbansal** [grails3-plugins/quartz#9]
@jeffbrown 
Currently the online documentation that I can see is of quartz-plugin but not of quartz3-plugin. I wanted to contribute to the documentation but am not sure which repository to contribute to.

Specifically I want to document that something like JobManagerService exists. I would have had an easier time if I had known that service existed.

**Comment by jeffscottbrown** [comment]
The docs are in this repo but not in the latest versions.  They need to be retrieved from earlier commits and put back in place.  Are you interested in taking that on?  If you are, that help would be greatly appreciated.  The docs are at https://github.com/grails3-plugins/quartz/tree/2e7e720fe720deafa1aa6326cf480c1eec08f5d0/src/docs.

Please let me know.  Thanks a lot for the feedback.

**Comment by anshbansal** [comment]
I am interested. Would be a good exercise about how to put docs on github. 

Can you elaborate a bit about getting from earlier commits? Maybe just a link to some place where I can read how to.

**Comment by jeffscottbrown** [comment]
Probably the simples thing would be to do something like this:

```
git clone git@github.com:grails3-plugins/quartz.git
cd quartz
git checkout 2e7e7
```

Then copy the docs from the `src/docs` directory.

**Comment by anshbansal** [comment]
Added the docs gdoc files in my fork.
https://github.com/anshbansal/quartz/commit/5fdabfab24eff769eaca6dcf8470fff713fd0b1d

Tried to generate them locally but the `grails doc` command was not found in Grails 3.0.2

**Comment by anshbansal** [comment]
Found about new way to use docs command in grails.
https://github.com/grails/grails-core/issues/9067#issuecomment-117494109

Will try and update.
